#!/usr/bin/env python3
"""
Worker module for processing queries with caching of plans.

This worker checks the cache for a plan before invoking the 35B model.
If the plan is found in cache, it returns the cached plan.
Otherwise, it would run the 35B model (stubbed) and store the result in cache.
"""

import os
import sys
import time
from typing import Any, Dict, Optional

# Import the cache module from the same directory
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
import cache


def normalize_and_hash(query: str, context: Optional[Dict[str, Any]] = None) -> str:
    """
    Normalize the query and context, then compute the SHA-256 hash to use as cache key.
    This mirrors the helper functions in cache.py but is kept here for encapsulation.
    """
    normalized = cache._normalize_query(query, context)
    return cache.hash_key(normalized)


def process_query(query: str, context: Optional[Dict[str, Any]] = None) -> Any:
    """
    Process a query by looking up the plan in cache or generating a new one.

    :param query: The user query string.
    :param context: Optional dictionary of contextual information.
    :return: The plan object (could be any JSON-serializable structure).
    """
    # Generate the cache key (plan_id) from query and context
    plan_id = normalize_and_hash(query, context)

    # Try to load the plan from cache
    cached_plan = cache.load_plan(plan_id)
    if cached_plan is not None:
        # Cache hit: return the cached plan
        print(f"[Worker] Cache hit for plan_id: {plan_id[:8]}...")
        return cached_plan

    # Cache miss: we would normally invoke the 35B model here.
    # For this stub, we generate a placeholder plan.
    print(f"[Worker] Cache miss for plan_id: {plan_id[:8]}... Generating new plan (stub).")

    # --- BEGIN STUB FOR 35B MODEL INFERENCE ---
    # In a real implementation, we would call the 35B model (e.g., via llama-server)
    # and obtain a plan. For now, we create a simple placeholder.
    # Example plan structure:
    # {
    #     "query": query,
    #     "context": context,
    #     "timestamp": int(time.time()),
    #     "steps": ["step1", "step2", "step3"],
    #     "result": "placeholder result from 35B model"
    # }
    # Uncomment the following lines and replace with actual model inference when ready.
    #
    # import subprocess
    # import json
    # # Example: call a local API or subprocess that runs the 35B model
    # # response = subprocess.check_output([...])
    # # plan_obj = json.loads(response)
    #
    # For the purpose of this stub, we create a dummy plan:
    plan_obj = {
        "query": query,
        "context": context or {},
        "timestamp": int(time.time()),
        "steps": [
            "Analyze query",
            "Retrieve relevant information",
            "Formulate response"
        ],
        "result": "This is a placeholder plan generated by the worker stub."
    }
    # --- END STUB FOR 35B MODEL INFERENCE ---

    # Store the newly generated plan in cache
    cache.store_plan(plan_id, plan_obj)
    print(f"[Worker] Stored new plan in cache with plan_id: {plan_id[:8]}...")

    return plan_obj


def main():
    """
    Example main loop for testing the worker.
    In a real deployment, this would be replaced by integration with the larger system.
    """
    print("Starting worker with caching...")
    # Initialize the cache database (creates table if not exists)
    cache.init_db()

    # Example queries for demonstration
    example_queries = [
        ("Controlla la posta elettronica per spam", {"user_id": "user123"}),
        ("Qual è il meteo oggi?", {"user_id": "user456", "location": "Roma"}),
        ("Controlla la posta elettronica per spam", {"user_id": "user123"}),  # Repeat to test cache hit
    ]

    for query, ctx in example_queries:
        print(f"\nProcessing query: '{query}' with context: {ctx}")
        start_time = time.time()
        plan = process_query(query, ctx)
        elapsed = time.time() - start_time
        print(f"Result: {plan}")
        print(f"Time taken: {elapsed:.2f} seconds\n")


if __name__ == "__main__":
    main()